name: dsalink

version: 3.0.0
description: >
  DSA IoT Platform - dsalink SDK for Dart. This package provides tools and libraries 
  for building IoT solutions using the Distributed Services Architecture (DSA) in Dart. 
  It includes support for secure communication, data serialization, and integration 
  with various IoT protocols and platforms.
homepage: "https://dsa.gencto.uk"
documentation: "https://dsa.gencto.uk/docs"

environment:
  sdk: ^3.8.1

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  pro_mpack: ^2.0.2
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lint: ^2.8.0
  test: ^1.26.2

executables:
  run_responder: bin/run_responder.dart

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
