name: dslink
version: 1.0.2
description: "DSA IoT Platform - DSLink SDK for Dart"
homepage: "http://iot-dsa.org"
documentation: "https://iot-dsa.github.io/docs/sdks/dart/"
dependencies:
  args: ^2.4.2
  logging: ^1.2.0
  crypto: ^3.0.3
  path: ^1.9.0
  msgpack_dart: ^1.0.1
  pointycastle: ^3.7.3
  json_diff: ^0.2.1
dev_dependencies:
  test: ^1.5.3
environment:
  sdk: ">=3.0.0"
