name: dsalink

version: 2.0.0
description: "DSA IoT Platform - dsalink SDK for Dart"
homepage: "http://iot-dsa.org"
documentation: "https://iot-dsa.github.io/docs/sdks/dart/"

dependencies:
  args: ^2.4.2
  logging: ^1.2.0
  crypto: ^3.0.3
  path: ^1.9.0
  pro_mpack: ^2.0.2
  pointycastle: ^4.0.0
  json_diff: ^0.2.1
  web: ^1.1.1
  http: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.5.3
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  influxdb_client: ^2.9.0

environment:
  sdk: ^3.7.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
